/*
Script used to copy the `public` folder, generated by Gatsby `build` command
to `docs` folder, used to deploy the site to Github Pages.
*/
const fs = require('fs-extra')
const path = require('path')

copyFolder('public', 'docs')
  .then(data =>
    console.log('Success! Next step: commit to deploy on Github Pages.')
  )
  .catch(err =>
    console.error('Unexpected error during server-side rendering', err)
  )

function copyFolder(folderSource, folderDest) {
  const source = path.resolve(process.cwd(), folderSource)
  const destination = path.resolve(process.cwd(), folderDest)
  return new Promise((resolve, reject) => {
    fs.copy(source, destination, (err, data) => {
      if (err) return reject(err)
      console.log(`${source} folder copied to ${destination}`)
      resolve(data)
    })
  })
}
